services:
  # --- DATABASE ---
  db:
    image: postgres:16
    container_name: postgres_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: courses_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  # --- APP ---
  app:
    build: .
    container_name: spring_app
    ports:
      - "4999:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/courses_db
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password123
    depends_on:
      - db

volumes:
  pgdata:
